# Goal
OperationCommand[] operations
---
# Result
uint16 error_code
string error_msg
uint16 operations_completed
uint16 operations_total

uint16 NONE=0
uint16 UNKNOWN_OPERATION=20001
uint16 OPERATION_FAILED=20002
uint16 CANCELLED=20003
---
# Feedback
string current_operation_name
uint16 operations_completed
uint16 operations_total
