# Goal
string behavior_tree
nav_msgs/Path path
nav2_operations_msgs/OperationAtPose[] operations_at_poses
---
# Result
std_msgs/Empty result
uint16 error_code
---
# Feedback
uint16 operations_completed
